In [1]:
import re
import nltk
import pandas as pd

In [2]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\andrew.labib\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [4]:
messages = pd.read_csv('SMSSpamCollection.txt', sep='\t', names=['Label', 'Message'])

In [5]:
messages

Label                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## Data Preprocessing

In [6]:
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [7]:
corpus = []

In [8]:
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['Message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [10]:
len(corpus)

5572

## TFIDF with N-Grams

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
tfidf = TfidfVectorizer(max_features=100)

In [13]:
X = tfidf.fit_transform(corpus).toarray()

In [14]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
X.shape

(5572, 100)

In [16]:
import numpy as np

In [17]:
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda X: "%.3g" % X))

In [18]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

## N-Grams

In [19]:
tfidf.vocabulary_

{'go': 22,
 'great': 26,
 'got': 25,
 'wat': 89,
 'ok': 58,
 'free': 18,
 'win': 93,
 'text': 77,
 'txt': 85,
 'say': 68,
 'already': 0,
 'think': 80,
 'life': 38,
 'hey': 29,
 'week': 91,
 'back': 5,
 'like': 39,
 'still': 73,
 'send': 70,
 'friend': 19,
 'prize': 63,
 'claim': 9,
 'call': 6,
 'mobile': 48,
 'co': 10,
 'home': 31,
 'want': 88,
 'today': 82,
 'cash': 8,
 'day': 14,
 'reply': 65,
 'www': 96,
 'right': 66,
 'take': 75,
 'time': 81,
 'message': 45,
 'com': 11,
 'oh': 57,
 'yes': 99,
 'make': 43,
 'way': 90,
 'dont': 16,
 'miss': 47,
 'ur': 87,
 'going': 23,
 'da': 13,
 'lor': 40,
 'meet': 44,
 'really': 64,
 'know': 34,
 'love': 41,
 'amp': 1,
 'let': 37,
 'work': 94,
 'yeah': 97,
 'tell': 76,
 'anything': 2,
 'thanks': 78,
 'uk': 86,
 'please': 61,
 'msg': 50,
 'see': 69,
 'pls': 62,
 'need': 52,
 'nokia': 55,
 'tomorrow': 83,
 'hope': 32,
 'well': 92,
 'lt': 42,
 'gt': 27,
 'get': 20,
 'ask': 3,
 'morning': 49,
 'happy': 28,
 'sorry': 72,
 'give': 21,
 'new': 53,
 'find

In [20]:
tfidf = TfidfVectorizer(max_features=500, ngram_range=(1,1))
X = tfidf.fit_transform(corpus).toarray()

In [21]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0.661, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.286, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.477, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [

In [22]:
tfidf.vocabulary_

{'go': 155,
 'point': 326,
 'great': 163,
 'world': 483,
 'got': 161,
 'wat': 461,
 'ok': 294,
 'lar': 210,
 'wif': 472,
 'free': 143,
 'entry': 125,
 'win': 475,
 'st': 395,
 'may': 247,
 'text': 410,
 'receive': 346,
 'question': 339,
 'txt': 444,
 'rate': 341,
 'apply': 19,
 'dun': 114,
 'say': 361,
 'early': 116,
 'already': 10,
 'think': 417,
 'life': 223,
 'around': 21,
 'though': 420,
 'hey': 183,
 'week': 465,
 'word': 480,
 'back': 32,
 'like': 224,
 'fun': 148,
 'still': 399,
 'xxx': 490,
 'send': 368,
 'even': 127,
 'brother': 48,
 'speak': 393,
 'per': 310,
 'set': 371,
 'friend': 144,
 'network': 278,
 'customer': 89,
 'selected': 367,
 'prize': 334,
 'claim': 69,
 'call': 53,
 'code': 74,
 'valid': 450,
 'hour': 190,
 'mobile': 261,
 'month': 264,
 'update': 446,
 'latest': 214,
 'colour': 77,
 'camera': 57,
 'co': 73,
 'gonna': 159,
 'home': 187,
 'soon': 390,
 'want': 459,
 'talk': 407,
 'stuff': 402,
 'tonight': 432,
 'enough': 124,
 'today': 426,
 'chance': 63,
 'cash

In [23]:
tfidf = TfidfVectorizer(max_features=500, ngram_range=(1,2))
X = tfidf.fit_transform(corpus).toarray()

In [24]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.661, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.286, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.477, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [

In [25]:
tfidf.vocabulary_

{'go': 153,
 'point': 331,
 'great': 163,
 'world': 483,
 'got': 161,
 'wat': 462,
 'ok': 297,
 'lar': 211,
 'wif': 473,
 'free': 140,
 'entry': 122,
 'win': 475,
 'st': 399,
 'may': 250,
 'text': 413,
 'receive': 350,
 'question': 343,
 'txt': 444,
 'rate': 345,
 'apply': 18,
 'dun': 112,
 'say': 364,
 'early': 114,
 'already': 9,
 'think': 420,
 'life': 225,
 'around': 20,
 'though': 422,
 'hey': 185,
 'week': 466,
 'word': 480,
 'back': 29,
 'like': 226,
 'fun': 146,
 'still': 402,
 'xxx': 490,
 'send': 371,
 'even': 124,
 'brother': 45,
 'speak': 397,
 'per': 312,
 'set': 375,
 'friend': 142,
 'network': 281,
 'customer': 86,
 'selected': 370,
 'prize': 338,
 'claim': 67,
 'call': 50,
 'code': 73,
 'valid': 450,
 'hour': 191,
 'mobile': 264,
 'month': 267,
 'update': 446,
 'latest': 215,
 'colour': 76,
 'camera': 56,
 'co': 71,
 'free call': 141,
 'gonna': 157,
 'home': 188,
 'soon': 393,
 'want': 460,
 'talk': 410,
 'stuff': 405,
 'tonight': 433,
 'enough': 121,
 'today': 428,
 'c

In [26]:
tfidf = TfidfVectorizer(max_features=500, ngram_range=(1,3))
X = tfidf.fit_transform(corpus).toarray()

In [27]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.661, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.286, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.243, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.477, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [

In [28]:
tfidf.vocabulary_

{'go': 152,
 'point': 330,
 'great': 162,
 'world': 483,
 'got': 160,
 'wat': 462,
 'ok': 296,
 'lar': 209,
 'wif': 473,
 'free': 139,
 'entry': 121,
 'win': 475,
 'st': 399,
 'may': 249,
 'text': 413,
 'receive': 350,
 'question': 343,
 'txt': 444,
 'rate': 345,
 'apply': 18,
 'dun': 111,
 'say': 363,
 'early': 113,
 'already': 9,
 'think': 420,
 'life': 223,
 'around': 20,
 'though': 422,
 'hey': 183,
 'week': 466,
 'word': 480,
 'back': 30,
 'like': 224,
 'fun': 145,
 'still': 402,
 'xxx': 490,
 'send': 370,
 'even': 123,
 'brother': 46,
 'speak': 397,
 'per': 311,
 'set': 374,
 'friend': 141,
 'network': 280,
 'customer': 86,
 'selected': 369,
 'prize': 337,
 'claim': 67,
 'call': 51,
 'code': 73,
 'valid': 450,
 'hour': 189,
 'mobile': 263,
 'month': 266,
 'update': 446,
 'latest': 213,
 'colour': 76,
 'camera': 57,
 'co': 71,
 'free call': 140,
 'gonna': 156,
 'home': 186,
 'soon': 392,
 'want': 460,
 'talk': 410,
 'stuff': 405,
 'tonight': 433,
 'enough': 120,
 'today': 428,
 'c

In [29]:
tfidf = TfidfVectorizer(max_features=500, ngram_range=(2,2))
X = tfidf.fit_transform(corpus).toarray()

In [30]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [31]:
tfidf.vocabulary_

{'free entry': 125,
 'rate apply': 339,
 'per request': 310,
 'copy friend': 78,
 'claim call': 54,
 'call claim': 24,
 'claim code': 55,
 'entitled update': 111,
 'update latest': 440,
 'latest colour': 217,
 'free call': 123,
 'call mobile': 32,
 'mobile update': 269,
 'chance win': 53,
 'win cash': 484,
 'reply hl': 346,
 'hl info': 188,
 'txt word': 435,
 'dont miss': 100,
 'ha ha': 176,
 'let know': 223,
 'feel like': 117,
 'mobile charged': 265,
 'go home': 148,
 'anything lor': 3,
 'call reply': 36,
 'nokia mobile': 288,
 'mobile free': 266,
 'free camcorder': 124,
 'please call': 317,
 'delivery tomorrow': 94,
 'lt gt': 241,
 'missed call': 263,
 'want go': 470,
 'first time': 122,
 'like lt': 227,
 'sm ac': 378,
 'etc free': 113,
 'bx ip': 21,
 'sorry call': 381,
 'call later': 30,
 'later meeting': 214,
 'way home': 475,
 'ok come': 299,
 'awarded bonus': 9,
 'prize call': 335,
 'send ur': 367,
 'ur awarded': 441,
 'hi babe': 185,
 'call free': 26,
 'thats cool': 416,
 'hi hi

In [32]:
tfidf = TfidfVectorizer(max_features=500, ngram_range=(2,3))
X = tfidf.fit_transform(corpus).toarray()

In [33]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [34]:
tfidf.vocabulary_

{'free entry': 129,
 'rate apply': 338,
 'claim call': 66,
 'call claim': 26,
 'claim code': 67,
 'call claim code': 27,
 'update latest': 444,
 'latest colour': 216,
 'free call': 126,
 'call mobile': 40,
 'call mobile update': 41,
 'chance win': 64,
 'win cash': 487,
 'reply hl': 344,
 'chance win cash': 65,
 'reply hl info': 345,
 'txt word': 437,
 'dont miss': 106,
 'ha ha': 180,
 'let know': 219,
 'feel like': 122,
 'go home': 149,
 'anything lor': 5,
 'call reply': 47,
 'nokia mobile': 290,
 'mobile free': 268,
 'free camcorder': 127,
 'please call': 313,
 'delivery tomorrow': 102,
 'lt gt': 240,
 'missed call': 265,
 'want go': 476,
 'first time': 125,
 'like lt': 222,
 'like lt gt': 223,
 'sm ac': 382,
 'bx ip': 23,
 'sorry call': 385,
 'call later': 37,
 'later meeting': 214,
 'sorry call later': 386,
 'call later meeting': 38,
 'awarded bonus': 14,
 'prize call': 331,
 'ur awarded': 445,
 'call free': 30,
 'thats cool': 419,
 'hi hi': 191,
 'call customer': 28,
 'customer ser

In [35]:
tfidf = TfidfVectorizer(max_features=500, ngram_range=(3,3))
X = tfidf.fit_transform(corpus).toarray()

In [36]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [37]:
tfidf.vocabulary_

{'free entry wkly': 141,
 'std txt rate': 387,
 'txt rate apply': 418,
 'set callertune caller': 363,
 'callertune caller press': 44,
 'caller press copy': 42,
 'press copy friend': 327,
 'copy friend callertune': 85,
 'call claim code': 27,
 'entitled update latest': 116,
 'update latest colour': 425,
 'free call mobile': 137,
 'call mobile update': 35,
 'mobile update co': 260,
 'update co free': 424,
 'chance win cash': 61,
 'reply hl info': 339,
 'like lt gt': 209,
 'bx ip pm': 25,
 'sorry call later': 378,
 'call later meeting': 33,
 'please call customer': 312,
 'call customer service': 28,
 'customer service representative': 95,
 'service representative pm': 362,
 'pm guaranteed cash': 319,
 'guaranteed cash prize': 171,
 'trying contact last': 415,
 'contact last weekend': 81,
 'last weekend draw': 204,
 'weekend draw show': 474,
 'draw show prize': 111,
 'show prize guaranteed': 365,
 'prize guaranteed call': 332,
 'guaranteed call claim': 169,
 'claim code valid': 66,
 'valid